### PR TITLE
linux-fslc: Upgrade to 5.12

### PR DESCRIPTION
**Pull request by Ossanes**
The 5.10 version was maintained as lts.

Signed-off-by: Vinicius Aquino <voa.aquino@gmail.com>

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
The defconfig files, inside the old `linux-fslc` need to be moved to the `linux-fslc-lts`; the new defconfig files need to be sync with the 5.12 ones.

**Comment by zandrey** [comment]
@Ossanes Can you keep the `PV` on a renamed `linux-fslc-lts` recipe as well?

**Comment by zandrey** [comment]
One additional question that came into my mind: how would the layer deal with the different entries in `KERNEL_DEVICETREE` for _LTS_ and _upstream_ kernels?

For now, there are no new DTB files that are present in `5.12`, but with later kernels on this might be the case. Since we set the `PREFERRED_PROVIDER_virtual/kernel` to `linux-fslc` based on `use-mainline-bsp` - this would require the layer to add those new DTBs into  `KERNEL_DEVICETREE`, thus making _LTS_ kernel build to fail once it would be overridden as a default kernel provider, as there is no machine override to add new DTBs conditionally.

Is there any solution that could address this problem now, or should it be addressed at the later stage once those discrepancies would appear?

-- andrey

**Comment by otavio** [comment]
@zandrey for now, we don't have a solution for it. It could be workaround using `KERNEL_DEVICETREE_use-mainline-bsp_pn-linux-fslc-lts` or similar.

In general, I'd prefer to support the newest kernel recipe and if someone needs lts they can "fix" it. Any idea how it could be handled?

**Comment by zandrey** [comment]
> Any idea how it could be handled?

Was my question exactly! 😄 I guess then we stay with the approach to keep both _LTS_ and _Mainline_ together until those discrepancies would appear and fix them at that point.

**Review by otavio — CHANGES_REQUESTED** [review]
@Ossanes please:

1) split the commit in two (one renaming the linux-fslc 5.10 to linux-fslc-lts and another with the new recipe)
2) we need to sync with the defconfig with any upstream changes, will call you to explain.

**Review by otavio — CHANGES_REQUESTED** [review]
Please use linux-fslc-lts-mfgtool.

**Comment by zandrey** [comment]
@Ossanes Thanks for splitting those up!

Can you please give more information in the commit description on how the migration of `defconfig` files has been performed? It would be beneficial for further tracking purposes, to see where the config is taken from.

See f008b4233b060aea18ed17c499fcb975fe60825b and 86a7903ffc77b6d7f07ea6c01ef133e2bf7b3b2b for examples of commit message bodies.

Also, for the new `linux-fslc_5.12.bb` introduction, it would be beneficial if you can indicate the upstream commit id in your commit message from which the config files are taken (see a6fd5a39fd58162b89425fc84bc69810ada355ba and 60d3bf09399924803a7440067144ca7f8dd01f42).

-- andrey

**Comment by zandrey** [comment]
@Ossanes Thanks for updating the description in commit messages!

As it can be seen now - you're using `defconfig` from _5.10_ version in _5.12_ build with a contract to align it with _5.12_ from upstream.

Can you also include this align commit to this PR? The reason being: if you try to build the _5.12_ with `defconfig` from _5.10_ - the kernel `do_configcheck` task might fail due to missing or not properly configured options. Adding a sync commit to this PR would ensure this failure would not happen, since the entire PR would be merged.

You can see the details of how the kernel config check is reported in https://github.com/Freescale/meta-freescale/pull/668#issuecomment-789796109, specifically the point [2] in the list.

-- andrey

**Comment by zandrey** [comment]
@Ossanes 

I've tried to build the `5.12` kernel version from `linux-fslc` repository standalone using exported SDK, and have following build errors for `arm32` architecture (**aarch64 build is fine**):

```
In file included from /opt/arm32-sdk/sysroots/x86_64-nxp-linux/usr/lib/arm-fsl-linux-gnueabi/gcc/arm-fsl-linux-gnueabi/10.2.0/plugin/include/gcc-plugin.h:28,
                 from /development/kernel/linux-fslc/scripts/gcc-plugins/gcc-common.h:7,
                 from /development/kernel/linux-fslc/scripts/gcc-plugins/arm_ssp_per_task_plugin.c:3:
/opt/arm32-sdk/sysroots/x86_64-nxp-linux/usr/lib/arm-fsl-linux-gnueabi/gcc/arm-fsl-linux-gnueabi/10.2.0/plugin/include/system.h:687:10: fatal error: gmp.h: No such file or directory
  687 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [/development/kernel/linux-fslc/scripts/gcc-plugins/Makefile:48: scripts/gcc-plugins/arm_ssp_per_task_plugin.so] Error 1
make[2]: *** [/development/kernel/linux-fslc/scripts/Makefile.build:514: scripts/gcc-plugins] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/development/kernel/linux-fslc/Makefile:1219: scripts] Error 2
make: *** [Makefile:215: __sub-make] Error 2
```

I was wondering if you've seen those as well, or is there something that I miss in my cross SDK setup?

FYI: Same SDK is used to build `5.10.x` without any issues.

-- andrey

**Comment by otavio** [comment]
@zandrey, which GCC is it? are you using a toolchain built on Yocto Project?

**Comment by zandrey** [comment]
> 
> 
> @zandrey, which GCC is it? are you using a toolchain built on Yocto Project?

Yes, it is the SDK generated by Yocto based on `imx6sxsabreauto` machine:
```
$ /opt/arm32-sdk/sysroots/x86_64-nxp-linux/usr/bin/arm-fsl-linux-gnueabi/arm-fsl-linux-gnueabi-gcc --version
arm-fsl-linux-gnueabi-gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I use this SDK to perform sanity builds on kernel updates, and so far all kernel versions were built OK with it. I started to see the build error only when I tried to compile `5.12` from `linux-fslc` repository.

-- andrey

**Comment by otavio** [comment]
That's interesting. I built it fine using our [yocto-env](https://github.com/OSSystems/docker-yocto-env), based on Ubuntu 20.04. This was based on GCC 9.3 as can be seen below:
```
% arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I built a fresh `meta-toolchain` on `hardknott`, for `imx6qdlsabresd` to verify if I could reproduce the issue. I tried to add the `gmp` library and it didn't help so it seems to be something specific to the OpenEmbedded toolchain. @kraj do you have any idea what might be missing?

**Comment by kraj** [comment]
Is nativesdk-gmp installed in SDK ?

**Comment by otavio** [comment]
> Is nativesdk-gmp installed in SDK ?

It wasn't but adding it didn't solve it as I ended with a missing symbol. I found a way to workaround it disabling the CONFiG_GCC_PLUGIN option so we avoid the error.

I sent an email with this to the OE-Core mailing list so we get more people aware of the issue.

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
@Ossanes, this looks great. Just to ensure it does work, please build the lttng to each of the platforms so we make sure it still builds as expected. Once you confirm that we can merge this.
